apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cockatoo-posts-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cockatoo-posts-api
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
