services:
  cockatoo-posts-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cockatoo-posts-api
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      # Database connection
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}

      # Search db connection
      - SEARCH_DB_USER=${SEARCH_DB_USER}
      - SEARCH_DB_PASSWORD=${SEARCH_DB_PASSWORD}
      - SEARCH_DB_HOST=${SEARCH_DB_HOST}
      - SEARCH_DB_DATABASE=${SEARCH_DB_DATABASE}

      # Betterstack monitoring
      - BETTERSTACK_SOURCETOKEN=${BETTERSTACK_SOURCETOKEN}

      # Azure Message Bus
      - BETTERSTACK_ENDPOINT=${BETTERSTACK_ENDPOINT}
      - COCKATOO_Q=${COCKATOO_Q}
      - COCKATOO_Q_USERNAME_TOPIC=${COCKATOO_Q_USERNAME_TOPIC}
    networks:
      - cockatoo-network

networks:
  cockatoo-network:
    external: true
