services:
  cockatoo-posts-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cockatoo-posts-api
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      - BETTERSTACK_SOURCETOKEN=${BETTERSTACK_SOURCETOKEN}
      - BETTERSTACK_ENDPOINT=${BETTERSTACK_ENDPOINT}
      - DB_USERID=${DB_USERID}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_SEARCH_USERID=${DB_SEARCH_USERID}
      - DB_SEARCH_PASSWORD=${DB_SEARCH_PASSWORD}
      - DB_SEARCH_SERVER=${DB_SEARCH_SERVER}
      - DB_SEARCH_PORT=${DB_SEARCH_PORT}
      - DB_SEARCH_DATABASE=${DB_SEARCH_DATABASE}
