services:
  cockatoo-posts-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cockatoo-posts-api
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      - DB_USERID=${DB_USERID}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
